#!/bin/bash
# Run code after installing the environment

# should extension manager be enabled?

## INSTALL JUPYTER LAB EXTENSIONS
conda install -y -c conda-forge jupyterlab_code_formatter black nb_conda_kernels
jupyter labextension install @ryantam626/jupyterlab_code_formatter --no-build
jupyter labextension install @jupyterlab/toc --no-build
jupyter labextension install @aquirdturtle/collapsible_headings --no-build

## BUILD
jupyter lab clean && jupyter lab build --dev-build=False


## IMPORT WORKSPACE
jupyter lab workspaces import binder/workspace.json

# Add a settings file? - ~/.jupyter/lab/user-settings
# https://github.com/ian-r-rose/binder-workspace-demo

# see https://github.com/jupyterlab/jupyterlab-demo for more ideas

## DOWNLOAD DATA

sudo apt install unzip
curl --output shapefiles.zip https://ac.ngi.be/remoteclient-open/SDI/NGI-IGN/fb1e2993-2020-428c-9188-eb5f75e284b9_x-shapefile_31370.zip
mkdir _data
unzip shapefiles.zip -d _data
rm shapefiles.zip
